Repository abhijeet007rocks8/Dev-Scripts, pull requests merged in 2022-03, with the labels that each got.

#66 Added Contributors List
  README.md
Labels: Level 1, GSSoC22, Completed 🥳

#51 Article scraper
  Python/Web Scraping/ArticleScraper/README.md
  Python/Web Scraping/ArticleScraper/Screen.gif
  Python/Web Scraping/ArticleScraper/scrape.py
Labels: Level 2, GSSoC22, Completed 🥳

#63 Added Weather App
  Web Development/Weather-App/README.md
  Web Development/Weather-App/Weather-App.jpg
  Web Development/Weather-App/index.html
  Web Development/Weather-App/script.js
  Web Development/Weather-App/style.css
Labels: Level 2, GSSoC22, Completed 🥳

#73 Crypto Scraper
  Go/Crypto-Scraper/README.md
  Go/Crypto-Scraper/main.go
Labels: Level 2, GSSoC22, Completed 🥳

#77 Command Line Password Generator using NodeJS
  NodeJS/CLI Password Generator/README.md
  NodeJS/CLI Password Generator/index.js
  NodeJS/CLI Password Generator/package-lock.json
  NodeJS/CLI Password Generator/package.json
  NodeJS/CLI Password Generator/utils/createPassword.js
  NodeJS/CLI Password Generator/utils/demo.gif
  NodeJS/CLI Password Generator/utils/savePassword.js
  NodeJS/README.md
Labels: Level 2, GSSoC22, Completed 🥳

#93 Google Clone Added
  Web Development/Google Clone/images/favicon.jpg
  Web Development/Google Clone/images/logo.jpg
  Web Development/Google Clone/index.html
  Web Development/Google Clone/main.js
  Web Development/Google Clone/readme.md
  Web Development/Google Clone/style.css
Labels: Level 3, GSSoC22, Completed 🥳

#45 Added Rules.md for documentation
  Rules.md
  assets/pic1.jpg
  assets/pic2.jpg
  assets/pic3.jpg
  assets/pic4.jpg
  assets/pic5.jpg
  assets/pic6.jpg
Labels: Level 1, GSSoC22, Completed 🥳

#80 Remove liked video in youtube
  Web Development/Script_to_remove_liked_videos_in_youtube/README.md
  Web Development/Script_to_remove_liked_videos_in_youtube/script.js
Labels: Level 2, GSSoC22, Completed 🥳

#116 PR to add a Ping pong game made in Java
  JAVA/Ping pong/Ball.java
  JAVA/Ping pong/GameFrame.java
  JAVA/Ping pong/GamePanel.java
  JAVA/Ping pong/Paddle.java
  JAVA/Ping pong/PongGame.java
  JAVA/Ping pong/README.md
  JAVA/Ping pong/Score.java
Labels: Level 3, GSSoC22, Completed 🥳

#110 Addition of issue and PR template
  .github/ISSUE_TEMPLATE/create-an-issue.yaml
  .github/pull_request_template.md
Labels: Level 2, GSSoC22, Completed 🥳

#109 To-do List (Python GUI)
  Python/To-do List/README.md
  Python/To-do List/addbox.py
  Python/To-do List/background_solid_purple_65808_1280x960.jpg
  Python/To-do List/images (1).jfif
  Python/To-do List/images.jfif
  Python/To-do List/main.py
  Python/To-do List/manruning-removebg-preview.png
  Python/To-do List/manrunning.jpg
Labels: Level 2, GSSoC22

#92 Added Tic Tac Toe
  Web Development/Tic-Tac-Toe Game/README.md
  Web Development/Tic-Tac-Toe Game/index.html
  Web Development/Tic-Tac-Toe Game/script.js
  Web Development/Tic-Tac-Toe Game/style.css
  Web Development/Tic-Tac-Toe Game/tictactoe-dark.png
  Web Development/Tic-Tac-Toe Game/tictactoe-light.png
Labels: Level 2, GSSoC22, Completed 🥳

#167 Added Billing System
  Python/Billing-System/Billing_System.py
  Python/Billing-System/README.md
  Python/Billing-System/requirements.txt
Labels: Level 3, GSSoC22, Completed 🥳

#98 Added note taking application using java
  JAVA/note-app/.gitignore
  JAVA/note-app/README.md
  JAVA/note-app/blob/add-demo.gif
  JAVA/note-app/blob/delete-all-demo.gif
  JAVA/note-app/blob/delete-demo.gif
  JAVA/note-app/blob/edit-demo.gif
  JAVA/note-app/blob/noteapp.png
  JAVA/note-app/note-app.iml
  JAVA/note-app/pom.xml
  JAVA/note-app/src/main/java/com/app/noteapp/NoteApplication.java
  JAVA/note-app/src/main/java/com/app/noteapp/controller/NoteApplicationController.java
  JAVA/note-app/src/main/java/com/app/noteapp/database/DatabaseConnection.java
  JAVA/note-app/src/main/java/com/app/noteapp/listener/NoteEventListener.java
  JAVA/note-app/src/main/java/com/app/noteapp/misc/Logger.java
  JAVA/note-app/src/main/java/com/app/noteapp/model/Note.java
  JAVA/note-app/src/main/java/com/app/noteapp/view/NoteView.java
  JAVA/note-app/src/main/java/module-info.java
  JAVA/note-app/src/main/resources/com/app/noteapp/note-application.fxml
  JAVA/note-app/src/main/resources/layout/note-view.fxml
Labels: Level 3, GSSoC22, Completed 🥳

#102 Week day calculator - script added
  Python/Week Day Calculator/DayExtractor.py
  Python/Week Day Calculator/README.md
Labels: Level 2, GSSoC22, Completed 🥳

#134 added offline password manager application
  Python/OfflinePasswordManager/Images/accessdata.png
  Python/OfflinePasswordManager/Images/addpass.png
  Python/OfflinePasswordManager/Images/addpassword.png
  Python/OfflinePasswordManager/Images/appicon.ico
  Python/OfflinePasswordManager/Images/backup.png
  Python/OfflinePasswordManager/Images/bar2.png
  Python/OfflinePasswordManager/Images/change.png
  Python/OfflinePasswordManager/Images/changinginfo.png
  Python/OfflinePasswordManager/Images/clipboard.png
  Python/OfflinePasswordManager/Images/cross.png
  Python/OfflinePasswordManager/Images/csv.png
  Python/OfflinePasswordManager/Images/database.png
  Python/OfflinePasswordManager/Images/dbpg.png
  Python/OfflinePasswordManager/Images/delpass.png
  Python/OfflinePasswordManager/Images/img1.png
  Python/OfflinePasswordManager/Images/img2.png
  Python/OfflinePasswordManager/Images/mainpg.png
  Python/OfflinePasswordManager/Images/mainwin.png
  Python/OfflinePasswordManager/Images/search.png
  Python/OfflinePasswordManager/Images/searchpg.png
  Python/OfflinePasswordManager/Images/securitypg.png
  Python/OfflinePasswordManager/Images/setupwin.png
  Python/OfflinePasswordManager/Images/shield.png
  Python/OfflinePasswordManager/Images/trash-bin.png
  Python/OfflinePasswordManager/README.md
  Python/OfflinePasswordManager/create_database.py
  Python/OfflinePasswordManager/passwordapp.py
  Python/OfflinePasswordManager/sending_email.py
  Python/OfflinePasswordManager/setup.py
Labels: Level 3, GSSoC22, Completed 🥳

#147 Added Customer_Review_Webapp files
  Web Development/Customer_Review_Webapp/app.py
  Web Development/Customer_Review_Webapp/readme.md
  Web Development/Customer_Review_Webapp/reviews.csv
  Web Development/Customer_Review_Webapp/templates/index.html
Labels: Level 3, GSSoC22, Completed 🥳

#159 Added Portfolio Website
  Web Development/Multiple Page Portfolio/README.md
  Web Development/Multiple Page Portfolio/images/banner.jpg
  Web Development/Multiple Page Portfolio/images/pic.jpg
  Web Development/Multiple Page Portfolio/images/profile.jpg
  Web Development/Multiple Page Portfolio/index.html
  Web Development/Multiple Page Portfolio/script.js
  Web Development/Multiple Page Portfolio/style.css
Labels: Level 2, GSSoC22, Completed 🥳

#175 A Python based Address-book
  Python/A Python based Address-book/README.md
  Python/A Python based Address-book/telemanager.py
Labels: Level 3, GSSoC22, Completed 🥳

#187 Added function plotter files
  Python/Function-Ploter/Examples_ScreenShots/Error_1.png
  Python/Function-Ploter/Examples_ScreenShots/Error_2.png
  Python/Function-Ploter/Examples_ScreenShots/Error_3.png
  Python/Function-Ploter/Examples_ScreenShots/Error_4.png
  Python/Function-Ploter/Examples_ScreenShots/Working_1.png
  Python/Function-Ploter/Examples_ScreenShots/Working_2.png
  Python/Function-Ploter/Examples_ScreenShots/Working_3.png
  Python/Function-Ploter/Plotter.py
  Python/Function-Ploter/README.md
  Python/Function-Ploter/requirements.txt
Labels: Level 3, GSSoC22

#189 Added cubic eq calc files
  Web Development/Cubic_Equation_Calc/assets/css/bootstrap.css
  Web Development/Cubic_Equation_Calc/assets/css/bootstrap.css.map
  Web Development/Cubic_Equation_Calc/assets/css/style.css
  Web Development/Cubic_Equation_Calc/index.html
  Web Development/Cubic_Equation_Calc/readme.md
  Web Development/Cubic_Equation_Calc/scripts/app.js
  Web Development/Cubic_Equation_Calc/scripts/bootstrap.bundle.js
  Web Development/Cubic_Equation_Calc/scripts/bootstrap.bundle.js.map
Labels: Level 3, GSSoC22

#160 Issue template
  .github/ISSUE_TEMPLATE/issue-template.yaml
Labels: Level 1, GSSoC22

#173 add-banking-system
  C++/Banking System/bankingsystem.cpp
  C++/Banking System/readme.md
Labels: Level 3, GSSoC22, Completed 🥳

#176 Prime Factor Calculator using Sieve of Eratosthenes
  Web Development/PrimeFactor_Calculator/README.md
  Web Development/PrimeFactor_Calculator/index.html
  Web Development/PrimeFactor_Calculator/script.js
  Web Development/PrimeFactor_Calculator/style.css
Labels: Level 2, GSSoC22, Completed 🥳

#184 Add increment decrement couter using ReactJS
  React/Counter/increment-decrement/.gitignore
  React/Counter/increment-decrement/README.md
  React/Counter/increment-decrement/package-lock.json
  React/Counter/increment-decrement/package.json
  React/Counter/increment-decrement/public/favicon.ico
  React/Counter/increment-decrement/public/index.html
  React/Counter/increment-decrement/public/logo192.png
  React/Counter/increment-decrement/public/logo512.png
  React/Counter/increment-decrement/public/manifest.json
  React/Counter/increment-decrement/public/robots.txt
  React/Counter/increment-decrement/src/App.css
  React/Counter/increment-decrement/src/App.js
  React/Counter/increment-decrement/src/App.test.js
  React/Counter/increment-decrement/src/Components/Counter.js
  React/Counter/increment-decrement/src/Components/style.css
  React/Counter/increment-decrement/src/index.css
  React/Counter/increment-decrement/src/index.js
  React/Counter/increment-decrement/src/logo.svg
  React/Counter/increment-decrement/src/reportWebVitals.js
  React/Counter/increment-decrement/src/setupTests.js
  React/Counter/readme.md
Labels: Level 2, GSSoC22, Completed 🥳

#185 Pong game
  Web Development/Pong_Game/index.html
  Web Development/Pong_Game/readme.md
  Web Development/Pong_Game/script.js
  Web Development/Pong_Game/style.css
Labels: Level 2, GSSoC22, Completed 🥳

#197 Weather teller
  Python/Weather-teller/.idea/.gitignore
  Python/Weather-teller/.idea/.name
  Python/Weather-teller/.idea/inspectionProfiles/Project_Default.xml
  Python/Weather-teller/.idea/inspectionProfiles/profiles_settings.xml
  Python/Weather-teller/.idea/misc.xml
  Python/Weather-teller/.idea/modules.xml
  Python/Weather-teller/.idea/project dev.iml
  Python/Weather-teller/README.md
  Python/Weather-teller/main.py
Labels: Level 2, GSSoC22, Completed 🥳

#198 Fixed typos in readme
  Python/Machine Learning/Disease_Predictor/README.md
Labels: Completed 🥳, no-level

#133 RockPaperScissors Game
  Python/rockPaperScissors/README.md
  Python/rockPaperScissors/demo.gif
  Python/rockPaperScissors/public/paper.png
  Python/rockPaperScissors/public/rock.png
  Python/rockPaperScissors/public/rps.png
  Python/rockPaperScissors/public/scissors.png
  Python/rockPaperScissors/rockPaperScissors.py
Labels: Level 2, GSSoC22

#192 Game added
  Web Development/Spock_Rock_Game/confetti.js
  Web Development/Spock_Rock_Game/index.html
  Web Development/Spock_Rock_Game/readme.md
  Web Development/Spock_Rock_Game/script.js
  Web Development/Spock_Rock_Game/style.css
Labels: Level 2, GSSoC22, Completed 🥳

#89 Auto SMS script added
  Python/Automations/Auto SMS/README.md
  Python/Automations/Auto SMS/demo.gif
  Python/Automations/Auto SMS/main.py
Labels: Level 2, GSSoC22, Completed 🥳

#138 Added Color Code Converter Files
  Web Development/Color_Code_Converter/assets/css/style.css
  Web Development/Color_Code_Converter/assets/media/Capture.PNG
  Web Development/Color_Code_Converter/index.html
  Web Development/Color_Code_Converter/readme.md
  Web Development/Color_Code_Converter/scripts/app.js
Labels: Level 2, GSSoC22, Completed 🥳

#203 tracksy added and readme format changed
  Web Development/tracksy/Capture.PNG
  Web Development/tracksy/README.md
  Web Development/tracksy/index.css
  Web Development/tracksy/index.html
  Web Development/tracksy/index.js
  Web Development/tracksy/manifest.json
Labels: Level 3, GSSoC22, Completed 🥳

#186 My lottery project
  React/lottery-react/.gitignore
  React/lottery-react/README.md
  React/lottery-react/package-lock.json
  React/lottery-react/package.json
  React/lottery-react/public/favicon.ico
  React/lottery-react/public/index.html
  React/lottery-react/public/logo192.png
  React/lottery-react/public/logo512.png
  React/lottery-react/public/manifest.json
  React/lottery-react/public/robots.txt
  React/lottery-react/src/App.css
  React/lottery-react/src/App.js
  React/lottery-react/src/index.css
  React/lottery-react/src/index.js
  React/lottery-react/src/logic/index.js
  React/lottery-react/src/logic/lottery.js
  React/lottery-react/src/logic/web3.js
  React/lottery-react/web/.env.example
  React/lottery-react/web/compile.js
  React/lottery-react/web/contracts/lottery.sol
  React/lottery-react/web/deploy.js
  React/lottery-react/web/package-lock.json
  React/lottery-react/web/package.json
  React/lottery-react/web/test/lottery.test.js
Labels: Level 3, GSSoC22, Completed 🥳

#168 Connect four
  Web Development/connect-four/DiagonalWin.png
  Web Development/connect-four/HorizontalWin.png
  Web Development/connect-four/Readme.md
  Web Development/connect-four/Starting.png
  Web Development/connect-four/Tie.png
  Web Development/connect-four/VerticalWin.png
  Web Development/connect-four/app.js
  Web Development/connect-four/index.html
  Web Development/connect-four/reset.png
  Web Development/connect-four/style.css
Labels: Level 2, GSSoC22, Completed 🥳

#211 Screen-recorder
  Python/Screen-recorder/.idea/.gitignore
  Python/Screen-recorder/.idea/.name
  Python/Screen-recorder/.idea/Screen recorder.iml
  Python/Screen-recorder/.idea/inspectionProfiles/Project_Default.xml
  Python/Screen-recorder/.idea/inspectionProfiles/profiles_settings.xml
  Python/Screen-recorder/.idea/misc.xml
  Python/Screen-recorder/.idea/modules.xml
  Python/Screen-recorder/README.md
  Python/Screen-recorder/main.py
Labels: Level 2, GSSoC22

#213 Image to pencil sketch
  Python/Image To Pencil Sketch/Dog.png
  Python/Image To Pencil Sketch/README.md
  Python/Image To Pencil Sketch/Sketch.png
  Python/Image To Pencil Sketch/main.py
Labels: Level 2, GSSoC22, Completed 🥳

#218 Add student data render
  React/student data render/ReadMe.md
  React/student data render/info/.gitignore
  React/student data render/info/README.md
  React/student data render/info/package-lock.json
  React/student data render/info/package.json
  React/student data render/info/public/favicon.ico
  React/student data render/info/public/index.html
  React/student data render/info/public/logo192.png
  React/student data render/info/public/logo512.png
  React/student data render/info/public/manifest.json
  React/student data render/info/public/robots.txt
  React/student data render/info/src/App.css
  React/student data render/info/src/App.js
  React/student data render/info/src/App.test.js
  React/student data render/info/src/Show.js
  React/student data render/info/src/index.css
  React/student data render/info/src/index.js
  React/student data render/info/src/logo.svg
  React/student data render/info/src/reportWebVitals.js
  React/student data render/info/src/setupTests.js
Labels: Level 3, GSSoC22, Completed 🥳

#214 Added Snake water and gun game in python
  Python/Snake_Water_Gun/README.md
  Python/Snake_Water_Gun/Snake_Water_Gun.py
Labels: Level 2, GSSoC22, Completed 🥳

#221 Added extra features to pr #218
  React/student data render/ReadMe.md
  React/student data render/info/src/App.css
  React/student data render/info/src/App.js
  React/student data render/info/src/Delete.js
  React/student data render/info/src/Show.js
Labels: GSSoC22, Completed 🥳, no-level

#210 Whatsapp timed bot [Issue #10]
  Python/Automations/WhatsappBotForTimedText/Demo.gif
  Python/Automations/WhatsappBotForTimedText/README.md
  Python/Automations/WhatsappBotForTimedText/messenger.py
Labels: Level2, GSSoC22, Completed 🥳
